version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: Moq
    versions:
    - 4.16.0
    - 4.16.1
  - dependency-name: coverlet.collector
    versions:
    - 3.0.2
    - 3.0.3
  - dependency-name: coverlet.msbuild
    versions:
    - 3.0.2
    - 3.0.3
  - dependency-name: NUnit
    versions:
    - 3.13.0
    - 3.13.1
